### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by czylzx** [benediamond/anonymous-zether#12]
Hello,
When Navigate to the protocol directory,in a second window,type truffle test,meet Error: Cannot find module 'fs/promises'.
Node.js version is v12.18.3.Run in Ubuntu18.Below this line,give the detailed error.
Require stack:
- /home/konjak/.nvm/versions/node/v12.18.3/lib/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.773292 (/home/konjak/.nvm/versions/node/v12.18.3/lib/node_modules/truffle/build/webpack:/external node-commonjs "fs/promises":1:1)

Wish you give me some advise to solve this problem.
Thanks for all the help

**Comment by benediamond** [comment]
hi. unfortunately, i do not maintain this repository anymore. however, there now appears be a production implementation of Anonymous Zether, called [Firn Protocol](https://github.com/firnprotocol), that you can try looking into.
